kotlin.code.style=official

org.gradle.jvmargs=-Xmx2g

#org.gradle.configuration-cache=true
#org.gradle.configuration-cache.problems=warn

org.jetbrains.dokka.experimental.tryK2=false
dokka_output_name=dokkaK2
#dokka_output_name=dokkaK1


#systemProp.dokka.shouldDisplayAllTypesPage=false

org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
#org.jetbrains.dokka.experimental.gradle.pluginMode=V2EnabledWithHelpers