kotlin.code.style=official

org.gradle.jvmargs=-Xmx2g

#dokka_version = 1.9.20-SNAPSHOT
#dokka_version = 1.9.20
dokka_version = 2.0.0-test-9fba5726c1918036cf00f8ea2d126ad45c57102a
#kotlin_version = 1.9.24
kotlin_version = 2.0.0

ktor_version=2.3.6

org.gradle.configuration-cache=true
#org.gradle.configuration-cache.problems=warn

#org.jetbrains.dokka.experimental.tryK2=false
#dokka_output_name=dokka20
#systemProp.dokka.shouldDisplayAllTypesPage=false