kotlin.code.style=official

org.gradle.jvmargs=-Xmx2g

#dokka_version = 1.9.20-SNAPSHOT
#dokka_version = 1.9.10
#dokka_version = 1.9.20
dokka_version = 2.0.0-test-49477c44dfc58e2702f4c145ff41190b39d117fb
#kotlin_version = 1.9.23
kotlin_version = 2.0.0-RC2

ktor_version=2.3.6

#org.gradle.unsafe.configuration-cache=true
#org.gradle.unsafe.configuration-cache-problems=warn

#org.jetbrains.dokka.experimental.tryK2=false
#dokka_output_name=k2
#systemProp.dokka.shouldDisplayAllTypesPage=false